[package]
name = "ebook_reader_cmdline"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# log 相关依赖
log = "0.4"
env_logger = "0.11.5"
chrono = "0.4"  # 用于格式化时间
